name: Build firmware

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/im-0/terrans-industry-onstep-firmware-ci:terrans-industry-v5-pro-eq5-2026-08-20

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Build OnStepX firmware
        run: HOME="/root" ./4-build-onstepx.sh

      - name: Build SmartHandController firmware
        run: HOME="/root" ./5-build-smarthandcontroller.sh

      - name: Build SmartWebServer firmware
        run: HOME="/root" ./6-build-smartwebserver.sh

      - name: Create firmware archive
        id: archive
        shell: bash
        run: |
          set -euo pipefail
          GIT_COMMIT="${GITHUB_SHA}"
          ARCHIVE_NAME="terrans-industry-v5-pro-eq5-$( date -u +%Y.%m.%d )-${GIT_COMMIT}"
          tar \
                  --create \
                  --xz \
                  --file "${ARCHIVE_NAME}.tar.xz" \
                  --transform "s,^,${ARCHIVE_NAME}/," \
                  -- \
                  "./OnStepX/build" "./SmartHandController/build" "./SmartWebServer/build"
          echo "name=${ARCHIVE_NAME}.tar.xz" >>"${GITHUB_OUTPUT}"

      - name: Upload firmware archive
        uses: actions/upload-artifact@v7
        with:
          name: '${{ steps.archive.outputs.name }}'
          path: '${{ steps.archive.outputs.name }}'
          if-no-files-found: 'error'
          archive: 'false'
